"""
    Background callbacks address the following limitations of long callbacks:
    - You can't access previous results returned by a long callback. This functionality is available in Dash Enterprise's Snapshot Engine.
    - If the Input/State/Output dependencies do not exist when the app starts (if they reference components that are generated by another callback), suppress_callback_exceptions=True does not prevent Dash from raising callback validation errors.
    
    """
